services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - makeyoubetter_mongo_data:/data/db

volumes:
  makeyoubetter_mongo_data:
